# Generated by Django 5.2 on 2025-12-05 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('account_number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Лицевой счёт')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('service_address', models.CharField(max_length=255, verbose_name='Адрес оказываемых услуг')),
                ('age', models.PositiveIntegerField(default=0, help_text='Возраст клиента в полных годах (необязательно)', verbose_name='Возраст клиента')),
                ('is_company', models.BooleanField(default=False, verbose_name='Юридическое лицо?')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='ФИО')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
            ],
            options={
                'verbose_name': 'Инженер',
                'verbose_name_plural': 'Инженеры',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название услуги')),
                ('service_type', models.CharField(choices=[('networks', 'Сеть передачи данных'), ('external_calls', 'Разговоры со сторонними операторами'), ('it_services', 'IT-услуги'), ('local_phone', 'Местная телефония'), ('ip_tv', 'IP-телевидение')], max_length=50, verbose_name='Тип услуги')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена услуги')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
        migrations.CreateModel(
            name='ClientService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(blank=True, max_length=25, unique=True, verbose_name='Номер услуги')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.client', verbose_name='Клиент')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга клиента',
                'verbose_name_plural': 'Услуги клиентов',
            },
        ),
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание проблемы')),
                ('priority_score', models.FloatField(default=50, verbose_name='Приоритет заявки')),
                ('engineer_visit_probability', models.FloatField(default=0, help_text='Автоматически рассчитанная вероятность необходимости выезда инженера.', verbose_name='Вероятность вызова инженера (0–100)')),
                ('proposed_solution', models.TextField(blank=True, help_text='Автоматически предложенное ИИ решение на основе похожих обращений. Как заметка оператору и инженеру.', null=True, verbose_name='Предложенное решение')),
                ('final_resolution', models.TextField(blank=True, help_text='Итоговое решение инженера после завершения работы по заявке.', null=True, verbose_name='Финальное решение проблемы')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Закрыта')], default='new', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='support.client', verbose_name='Клиент')),
                ('engineer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='support.engineer', verbose_name='Инженер')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
