# Generated by Django 5.2 on 2025-12-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='engineer_visit_probability',
            field=models.PositiveSmallIntegerField(default=0, help_text='Целое число процентов.', verbose_name='Вероятность вызова инженера (0–100)'),
        ),
    ]
