# Generated by Django 5.2 on 2025-12-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_supportticket_engineer_visit_probability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportticket',
            name='priority_score',
            field=models.PositiveSmallIntegerField(default=50, verbose_name='Приоритет заявки'),
        ),
    ]
