# Generated by Django 5.2 on 2025-12-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_supportticket_priority_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='ticket_code',
            field=models.CharField(blank=True, max_length=12, unique=True, verbose_name='ID заявки'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='final_resolution',
            field=models.TextField(blank=True, null=True, verbose_name='Финальное решение проблемы'),
        ),
        migrations.AlterField(
            model_name='supportticket',
            name='proposed_solution',
            field=models.TextField(blank=True, null=True, verbose_name='Предложенное решение'),
        ),
    ]
