# Generated by Django 5.2 on 2025-12-05 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0004_supportticket_ticket_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supportticket',
            name='proposed_solution',
        ),
        migrations.AddField(
            model_name='supportticket',
            name='proposed_solution_client',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендация клиенту'),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='proposed_solution_engineer',
            field=models.TextField(blank=True, null=True, verbose_name='Техническое решение (для инженера)'),
        ),
    ]
