# Generated by Django 5.2 on 2025-12-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_remove_supportticket_proposed_solution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='why_engineer_needed',
            field=models.TextField(blank=True, null=True, verbose_name='Почему требуется инженер'),
        ),
    ]
