# Generated by Django 5.2 on 2025-12-05 15:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Момент создания записи в журнале логов.', verbose_name='Дата и время записи')),
                ('level', models.CharField(help_text='Уровень важности записи (например: INFO, ERROR, WARNING).', max_length=10, verbose_name='Уровень')),
                ('message', models.TextField(help_text='Основной текст лог-записи.', verbose_name='Сообщение')),
                ('logger_name', models.CharField(default='unknown', help_text='Имя или источник, откуда пришло сообщение.', max_length=255, verbose_name='Имя логгера')),
                ('traceback', models.TextField(blank=True, help_text='Полная трассировка исключения, если применимо.', verbose_name='Трассировка ошибки')),
                ('extra_data', models.JSONField(blank=True, help_text='Дополнительные параметры, переданные в лог (формат JSON).', null=True, verbose_name='Дополнительные данные')),
            ],
            options={
                'verbose_name': 'Запись лога',
                'verbose_name_plural': 'Журнал логов',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(help_text='Уникальный адрес электронной почты пользователя.', max_length=254, unique=True, verbose_name='Почта')),
                ('full_name', models.CharField(help_text='Укажите фамилию и имя полностью.', max_length=255, verbose_name='Полное имя')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Сотрудник?')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['id'],
            },
        ),
    ]
