# Generated by Django 5.2 on 2025-12-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_text', models.TextField(db_index=True, unique=True, verbose_name='Source text')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last updated at')),
                ('text_ru', models.TextField(blank=True, null=True, verbose_name='Text in Русский')),
                ('text_en', models.TextField(blank=True, null=True, verbose_name='Text in English')),
                ('text_kk', models.TextField(blank=True, null=True, verbose_name='Text in Қазақша')),
            ],
            options={
                'verbose_name': 'Переводы',
                'verbose_name_plural': 'Переводы',
                'ordering': ['source_text'],
            },
        ),
    ]
